#! /bin/csh -f
#

set NUMBER_OF_PROCESSORS  = 9
set TEMPERATURE           = 2
set NUMBER_OF_CYCLES      = 10000
set NUMBER_OF_PARTICLES   = 10000
set RCUT                  = 0.1
set REPULSIVE_CST         = 1
set GRIDSIZE              = 3
set DEBUG                 = f

clear


if ($DEBUG == 'GDB') then
  
  @ x = ( $NUMBER_OF_PROCESSORS - 1)
  mpirun -np 1 gdb --args ./pdm $NUMBER_OF_PROCESSORS $TEMPERATURE $NUMBER_OF_CYCLES $NUMBER_OF_PARTICLES $RCUT $REPULSIVE_CST $GRIDSIZE : -np $x ./pdm $NUMBER_OF_PROCESSORS $TEMPERATURE $NUMBER_OF_CYCLES $NUMBER_OF_PARTICLES $RCUT $REPULSIVE_CST $GRIDSIZE 
  
else if ($DEBUG == 'valgrind') then

  mpirun -np $NUMBER_OF_PROCESSORS valgrind --leak-check=full --track-origins=yes --suppressions=/usr/share/openmpi/openmpi-valgrind.supp ./pdm $NUMBER_OF_PROCESSORS $TEMPERATURE $NUMBER_OF_CYCLES $NUMBER_OF_PARTICLES $RCUT $REPULSIVE_CST $GRIDSIZE

else

  mpirun -np $NUMBER_OF_PROCESSORS ./pdm $NUMBER_OF_PROCESSORS $TEMPERATURE $NUMBER_OF_CYCLES $NUMBER_OF_PARTICLES $RCUT $REPULSIVE_CST $GRIDSIZE

endif



exit