#! /bin/csh -f
#

set NUMBER_OF_PROCESSORS  = 9
set TEMPERATURE           = 1
set NUMBER_OF_CYCLES      = 500
set NUMBER_OF_PARTICLES   = 750
set RCUT                  = 1.0
set REPULSIVE_CST         = 5
set GRIDSIZE              = 3
set DELTAT                = 0.001
set INITIALISATION_STEPS  = 10
set DEBUG                 = f

clear
make clean
make


if ($DEBUG == 'GDB') then
  
  @ x = ( $NUMBER_OF_PROCESSORS - 1)
  mpirun -np 1 gdb --args ./pdm $NUMBER_OF_PROCESSORS $TEMPERATURE $NUMBER_OF_CYCLES $NUMBER_OF_PARTICLES $RCUT $REPULSIVE_CST $GRIDSIZE : -np $x ./pdm $NUMBER_OF_PROCESSORS $TEMPERATURE $NUMBER_OF_CYCLES $NUMBER_OF_PARTICLES $RCUT $REPULSIVE_CST $GRIDSIZE $DELTAT $INITIALISATION_STEPS
  
else if ($DEBUG == 'valgrind') then

  mpirun -np $NUMBER_OF_PROCESSORS valgrind --leak-check=full --track-origins=yes --suppressions=/usr/share/openmpi/openmpi-valgrind.supp ./pdm $NUMBER_OF_PROCESSORS $TEMPERATURE $NUMBER_OF_CYCLES $NUMBER_OF_PARTICLES $RCUT $REPULSIVE_CST $GRIDSIZE $DELTAT $INITIALISATION_STEPS

else

  mpirun -np $NUMBER_OF_PROCESSORS ./pdm $NUMBER_OF_PROCESSORS $TEMPERATURE $NUMBER_OF_CYCLES $NUMBER_OF_PARTICLES $RCUT $REPULSIVE_CST $GRIDSIZE $DELTAT $INITIALISATION_STEPS 2> log.txt

endif



exit
